Updated to support kde4.

diff --git a/install_fuseisomenu b/install_fuseisomenu
--- a/install_fuseisomenu
+++ b/install_fuseisomenu
@@ -1,16 +1,12 @@
 #!/bin/bash
 instfiles="fuseisomenu.desktop fuseisomenu.sh"
-KDEAPPSDIR="${HOME}/.kde/share/apps"
+KDE4SRVDIR="${HOME}/.kde/share/kde4/services"
+MENUDIR="${KDE4SRVDIR}/ServiceMenus"
 
-for app in konqueror d3lphin dolphin; do
-    APPDIR="${KDEAPPSDIR}/${app}"
-    MENUDIR="${APPDIR}/servicemenus"
-
-    if [ -d $APPDIR ]; then
-        mkdir -p ${MENUDIR} 2>/dev/null    # doesnt pre-exist for dolphin
-        echo -n "Installing menu to $MENUDIR ... "
-        cp -a $instfiles ${MENUDIR}
-        [ $? -eq 0 ] && echo "OK" || echo "FAILED"
-    fi
-done
+if [ -d $KDE4MENUDIR ]; then
+    mkdir -p ${MENUDIR} 2>/dev/null
+    echo -n "Installing menu to $MENUDIR ... "
+    cp -a $instfiles ${MENUDIR}
+    [ $? -eq 0 ] && echo "OK" || echo "FAILED"
+fi
 echo
